In [1]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv('finaldataframe.csv')
data

,Unnamed: 0,gid,black,white,black_rating,white_rating,move_list,winner
0,0,1939599,fastplayer,Maciej Celuch,1806,2688,g3*e9i10f7d12b12c11d11c12f11g12e12g5j4h7c9h3f5...,white
1,1,1938419,MoHex3H,Maciej Celuch,1500,2688,h12e4f4i5h6e9i7i6h7g5k5k4j4j5h5i3i4k2j2j3f7e6h...,white
2,2,1938296,fastplayer,Maciej Celuch,1806,2688,g7*f7d10i8j11f8g6i5h4j3j4i4g8j6j5e10f11i6h9g10...,white
3,3,1938295,Jose Maria Grau Ribas,Maciej Celuch,2083,2688,a4*c3i10f8j2k10k11i3e6g6f10e10f9e9d12e11e12f11...,white
4,4,1938291,MoHex3H,Maciej Celuch,1500,2688,g7*e8e4c5f6j5i10h9g11g6f9h11h10d10d9c8b12f10g9...,white
...,...,...,...,...,...,...,...,...
45441,61527,5762,Robert Butler,Jonas,1142,1546,d7*i4g7j7j5i6i5e5f6d7e4f4g2g3h2h3i2k3l1k1j3k2j...,white
45442,61528,5761,Max DeWolf,Robert Butler,1448,1142,g7g8e8e9j8i7k6j4j5h5l3i11k10l2k3k2j3j2i3i2h3h2...,white
45443,61530,5176,Robert Butler,bachkiesel,1142,1621,e4*e5d7e7e6g5g3h3e8d8d9g7f10i9h8k6k4j6i6j5j4i5...,white
45444,61531,5175,Rabid Wolff,Robert Butler,1471,1142,g7g8e9e10f8f9d9d10b11c10b10c9b9c8b8c6c7d6d7f5d...,white
45445,61532,5173,Robert Butler,shawn,1142,1252,h7c13g12d10h10g5h5g11h11f13g13h9j8h4k5e12i4,black

In [13]:
data = data[data['move_list'].str.len() >= 6]
data = data[~data['move_list'].str.contains('*', regex=False)]
data

,Unnamed: 0,gid,black,white,black_rating,white_rating,move_list,winner
1,1,1938419,MoHex3H,Maciej Celuch,1500,2688,h12e4f4i5h6e9i7i6h7g5k5k4j4j5h5i3i4k2j2j3f7e6h...,white
8,8,1877594,Daniel Sepczuk,Maciej Celuch,2386,2688,c12e4i5j4d5e9e5d3b3d4b6b4i4h8j9h7f7e10,white
12,12,1872780,Maciej Celuch,Arek Kulczycki,2688,2542,c2e9j9f7h6j10k9k11g8i10f10h7g7j2j3i3d5g4g5h5g6...,black
13,13,1872777,Yorge,Maciej Celuch,1520,2688,a3i10h9f8i5g11k10k9j10j9f10e12d11b12c12e10d8e7...,white
14,14,1861986,Maciej Celuch,shalev,2688,2491,c12e4i5i10e8d11j9j11k11j12l11k10l8m9d4e3c3d2b3...,black
...,...,...,...,...,...,...,...,...
45435,61518,6900,debbie,Robert Butler,1440,1142,b5d7b6b7f7g5,white
45439,61525,5824,Martin,Robert Butler,1602,1142,l12l11f6f9e9e10d10c12b12c11b11c10b10c9b9c8b8d6...,black
45442,61528,5761,Max DeWolf,Robert Butler,1448,1142,g7g8e8e9j8i7k6j4j5h5l3i11k10l2k3k2j3j2i3i2h3h2...,white
45444,61531,5175,Rabid Wolff,Robert Butler,1471,1142,g7g8e9e10f8f9d9d10b11c10b10c9b9c8b8c6c7d6d7f5d...,white
45445,61532,5173,Robert Butler,shawn,1142,1252,h7c13g12d10h10g5h5g11h11f13g13h9j8h4k5e12i4,black

In [21]:
df = pd.DataFrame(columns=['state', 'action'])
i = 0
for _, row in data.iterrows():
    move_list = row['move_list']
#     print(move_list)
    prefix = ''
    idx = 1
    prefix+=move_list[0]
    while move_list[idx].islower() == False:
        prefix+=move_list[idx]
        idx+=1
    next_move = move_list[idx]
    idx+=1
    while idx<len(move_list):
        while (move_list[idx].islower() == False):
            next_move+=move_list[idx]
            idx+=1
            if idx==len(move_list):
                break
        df.loc[i] = [prefix] + [next_move]
        i+=1
        prefix += next_move
        if idx<len(move_list):
            next_move = move_list[idx]
            idx+=1

In [22]:
df

                                            state action
0                                             h12     e4
1                                           h12e4     f4
2                                         h12e4f4     i5
3                                       h12e4f4i5     h6
4                                     h12e4f4i5h6     e9
...                                           ...    ...
807668           h7c13g12d10h10g5h5g11h11f13g13h9     j8
807669         h7c13g12d10h10g5h5g11h11f13g13h9j8     h4
807670       h7c13g12d10h10g5h5g11h11f13g13h9j8h4     k5
807671     h7c13g12d10h10g5h5g11h11f13g13h9j8h4k5    e12
807672  h7c13g12d10h10g5h5g11h11f13g13h9j8h4k5e12     i4

[807673 rows x 2 columns]

In [23]:
df.to_csv('state_action.csv')